### ISSUE TITLE
An overlay behind the context menu when opening to click outside to close

### ISSUE THREAD

**Issue by Songkeys** [icflorescu/mantine-contextmenu#120]
**Is your feature request related to a problem? Please describe.**

When user wants to close the context menu, the most common way to do it is to click outside of it like what we do with modals. You may experience this in most applications. But the current implementation of the library does not, which makes the closing unexpected - e.g. might click somewhere triggle-able for an unwanted action.

**Describe the solution you'd like**

Added an invisible overlay behind the context menu, so that when clicking "outside", we hide the context menu.

**Describe alternatives you've considered**

Developers can also implement themselves but this requires some work.

**Additional context**

I could help to make a PR if you think this is reasonable.

**Comment by icflorescu** [comment]
Sounds perfectly reasonable.
Make sure to target the `next` branch in the PR.
Thanks a lot!
