### ISSUE TITLE
Triggering outside of onContextMenu

### ISSUE THREAD

**Issue by baegmon** [icflorescu/mantine-contextmenu#143]
Hello, just wondering if there is a way to trigger the context menu outside of **onContextMenu**?

In this [sample](https://codesandbox.io/p/sandbox/agitated-fermat-jynfcj?file=%2Fsrc%2FApp.tsx%3A40%2C1-41%2C1) using ReactFlow, I try to open a context menu when I drag the dot to an empty space on the canvas which is not successful. **onContextMenu** implementation is confirmed working by right clicking any space on the canvas.

Just wondering if there is a way to approach this?

**Comment by icflorescu** [comment]
The `showContextMenu` returns a `React.MouseEventHandler`, which is a function that accepts a `MouseEvent` as parameter, see the type definitions here: https://icflorescu.github.io/mantine-contextmenu/type-definitions/.

In your case, this means you'll have to call it with the `e` you're getting from `onConnectEnd`. I've adjusted your example to work: https://codesandbox.io/p/sandbox/agitated-fermat-forked-jmtm4m?file=%2Fsrc%2FApp.tsx%3A47%2C1-48%2C1

Also, be careful to read and understand the styling guide at https://icflorescu.github.io/mantine-contextmenu/styling/. In your example, in `index.tsx` you were importing the non-layered `mantine` styles and the layered `mantine-contextmenu` ones. Choose one approach and be consistent.
