### ISSUE TITLE
Ability to style or replace submenu arrow icon

### ISSUE THREAD

**Issue by JTson8** [icflorescu/mantine-contextmenu#146]
Hello, 
I was wondering if there was anyway to style the arrow icon that gets rendered for submenus? 
Would also be great to even have the ability to replace the icon entirely with a different one.

![image](https://github.com/icflorescu/mantine-contextmenu/assets/36866335/9a814ea2-b0f9-4895-896c-53d93dc27447)

**Comment by JTson8** [comment]
I added this possibility myself now with a new property `iconRight`.
This is done in the PR #147

**Comment by icflorescu** [comment]
Thanks a lot for taking the time to come up with the PR, @JTson8!
This landed in `7.6.1` 🎉
