### ISSUE TITLE
Handling context menus of nested elements

### ISSUE THREAD

**Issue by yverby** [icflorescu/mantine-contextmenu#18]
**Is your feature request related to a problem? Please describe.**

I ran into a small issue when there are several elements nested inside each other and each of these elements has its own context menu. Then, unless you call `stopPropagation` method on the inner element, the context menu of element will always display the context menu of the outer element.

https://codesandbox.io/s/xenodochial-cohen-fsj6wr

**Describe the solution you'd like**

Perhaps it would be better to do prevent propagation on the package side?

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by icflorescu** [comment]
Well spotted, thank you!
This will be fixed in a few minutes, as soon as `v1.2.3` hits the npm registry.

**Comment by icflorescu** [comment]
Done.
