### ISSUE TITLE
Expose the `ContextMenu` component

### ISSUE THREAD

**Issue by DelegatorMooned** [icflorescu/mantine-contextmenu#45]
**Is your feature request related to a problem? Please describe.**
I have a context menu event doesn't use on the React's `useContext` and I umsure on how to use the `mantine-contextmenu` library with this constraint.

**Describe the solution you'd like**
I would like to render the `ContextMenu` component manually but it's not accessible on import.

**Describe alternatives you've considered**
Considering copy-pasting the components for the meantime.

Thank you very much for your work!

**Comment by icflorescu** [comment]
Thank you for your kind words!
The `ContextMenu`, `ContextMenuItem` and `ContextMenuDivider` components are exposed starting with `v.1.3.0`.
