### ISSUE TITLE
[Feature] Sub Menus

### ISSUE THREAD

**Issue by Corvimia** [icflorescu/mantine-contextmenu#68]
**Is your feature request related to a problem? Please describe.**
When there are a lot of actions on a single item, it tends to make the context menu really tall, and sometimes too much for smaller screens.

**Describe the solution you'd like**
I would like something like Windows or Mac, where there's the ability to have sub menus in the context menu.
<img width="544" alt="image" src="https://github.com/icflorescu/mantine-contextmenu/assets/11447349/f1131f89-fe99-4a6f-ba3f-08590526472e">

**Describe alternatives you've considered**
Scrollable menu. It would help with the issue, but would be an unusual UX for the user.

**Additional context**
N/A

**Comment by Corvimia** [comment]
@icflorescu I'm trying to give it a go, but I'm struggling to get the project to run on my machine. I've got the right yarn & node version, but running `yarn dev` in the root folder generates that error:
<img width="1285" alt="image" src="https://github.com/icflorescu/mantine-contextmenu/assets/11447349/a120ffcd-09db-4849-b05a-7cbecf2b3f75">

I've also tried to run `yarn build` beforehand but it's still not working. 

I know issues aren't really the place to discuss problems like that, but I wasn't sure where to ask for help.

**Comment by icflorescu** [comment]
Hey @Corvimia,

This is a missing feature I was planning to address at some point in the future.
Due to an unfortunate event in my family, I am unable to work for the next few days, so I am more than grateful if you can give it a go.

Good catch regarding the node version.

Thanks a lot! 🙏❤️
